// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('mytest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('mytest', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1256, height: 773 })
    await driver.findElement(By.name("email")).sendKeys("nivish@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("123")
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.name("email")).sendKeys("nivish@gmail.com")
    await driver.findElement(By.name("password")).sendKeys("123")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.id("input")).click()
    await driver.findElement(By.id("input")).sendKeys("dart")
    await driver.findElement(By.css(".btn-secondary")).click()
    await driver.findElement(By.linkText("2 https://stackoverflow.com/questions/70947231/how-can-i-return-string-value-from-list-by-its-name-value-in-dart-list")).click()
  })
})
